server:
  port: 8081

mail:
  external:
    #ip: 192.168.0.1
    url: "https://ti-timeserver.herokuapp.com/api/v1/email/receiveExternalMail"
    key: "letMeIn"

featureswitch:
  printIp: true
  emailUp: true

feature-switch:
  receive-external-mail:
    receive-external-mail-on: true
  send-external-mail:
    send-external-mail-on: true